title: Ajith Kumar Ethirajulu # your name (or website title) here
logo: "/images/20230519_110121%20(2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hey, Ajith here. Currently pursuing MS Data Science at University at Buffalo. Skills: ML, Deep learning, SQL, Power BI, Tableau, Analytics. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/aje2907/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-8DP7TZPDDV # your Google Analytics tracking ID here
colors:
  crimson: '#900C3F'
